### ISSUE TITLE
Checking doesn't pick capital letters as errors in status values

### ISSUE THREAD

**Issue by IanCarle** [FieldStudiesCouncil/tombiovis#44]
No errors are generated but character is ignored if Key is used as a value instead of key in the status column of the characters tab v1.8.2

**Comment by burkmarr** [comment]
Thanks Ian. This  catches a lot of people out. I will address it, but instead of catching and reporting it, I may just review all of these type of configuration values and make them all non-case sensitive.

Rich

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checking doesn't pick capital letters as errors in status values](https://trello.com/c/64iKqlte/206-checking-doesnt-pick-capital-letters-as-errors-in-status-values)

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Eliminate inappropriate case sensitivity from Identikit to make it more resilient.](https://trello.com/c/VymGj2iC/225-eliminate-inappropriate-case-sensitivity-from-identikit-to-make-it-more-resilient)

**Comment by burkmarr** [comment]
Version 1.9.0 released.
